import re
from dataclasses import dataclass

_AI_PATTERNS: list[tuple[re.Pattern, str, str]] = [
    # (regex, classification, tool_name)
    (re.compile(r"co-authored-by:\s*claude", re.IGNORECASE), "ai_claude", "Claude"),
    (re.compile(r"co-authored-by:.*anthropic", re.IGNORECASE), "ai_claude", "Claude"),
    (re.compile(r"co-authored-by:.*github[\s-]*copilot", re.IGNORECASE), "ai_copilot", "GitHub Copilot"),
    (re.compile(r"co-authored-by:.*copilot", re.IGNORECASE), "ai_copilot", "GitHub Copilot"),
    (re.compile(r"co-authored-by:.*cursor", re.IGNORECASE), "ai_cursor", "Cursor"),
    (re.compile(r"co-authored-by:.*codex", re.IGNORECASE), "ai_codex", "Codex"),
    (re.compile(r"co-authored-by:.*openai", re.IGNORECASE), "ai_codex", "OpenAI"),
    (re.compile(r"co-authored-by:.*aider", re.IGNORECASE), "ai_aider", "Aider"),
    (re.compile(r"co-authored-by:.*cody", re.IGNORECASE), "ai_cody", "Sourcegraph Cody"),
    (re.compile(r"co-authored-by:.*devin", re.IGNORECASE), "ai_devin", "Devin"),
    (re.compile(r"co-authored-by:.*gemini", re.IGNORECASE), "ai_gemini", "Gemini"),
    (re.compile(r"co-authored-by:.*windsurf", re.IGNORECASE), "ai_windsurf", "Windsurf"),
    # Generic "generated by" patterns in commit messages
    (re.compile(r"generated\s+(?:by|with|using)\s+claude", re.IGNORECASE), "ai_claude", "Claude"),
    (re.compile(r"generated\s+(?:by|with|using)\s+copilot", re.IGNORECASE), "ai_copilot", "GitHub Copilot"),
    (re.compile(r"generated\s+(?:by|with|using)\s+cursor", re.IGNORECASE), "ai_cursor", "Cursor"),
    (re.compile(r"generated\s+(?:by|with|using)\s+ai", re.IGNORECASE), "ai_other", "Unknown AI"),
    (re.compile(r"created\s+(?:by|with|using)\s+ai", re.IGNORECASE), "ai_other", "Unknown AI"),
]


@dataclass
class TagDetectionResult:
    classification: str  # 'human', 'ai_claude', 'ai_copilot', etc.
    tool_name: str | None  # Human-readable tool name
    confidence: float  # 1.0 for tag matches
    detected: bool


def detect_ai_tags(commit_message: str) -> TagDetectionResult:
    """Check commit message for known AI co-author tags and patterns."""
    if not commit_message:
        return TagDetectionResult(
            classification="human", tool_name=None, confidence=1.0, detected=False
        )

    for pattern, classification, tool_name in _AI_PATTERNS:
        if pattern.search(commit_message):
            return TagDetectionResult(
                classification=classification,
                tool_name=tool_name,
                confidence=1.0,
                detected=True,
            )

    return TagDetectionResult(
        classification="human", tool_name=None, confidence=1.0, detected=False
    )
